<?php

namespace tuto\BackofficeBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByetat()
	{
		$query = $this->createQueryBuilder('c');
		$query->SELECT ('c') ;
		$query->where('c.etat = 1');
		
        return $query->getQuery()->getResult();
	}

	 public function count()
	{
		$query = $this->createQueryBuilder('n');
		$query->SELECT ('COUNT(n)');
		$query->where('n.etat = 1');
        return $query->getQuery()->getSingleScalarResult();
        
	}
}
