<?php

namespace tuto\BackofficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationReponseRepository extends EntityRepository
{
     public function getEvaluation($user_id) {
        $query = $this->createQueryBuilder("d");
        $query->select('d');
      
        $query->Where($query->expr()->in('d.id', "SELECT d2.id FROM tuto\BackofficeBundle\Entity\EvaluationReponse d2 INNER JOIN d2.evaluation p WHERE p.user = :user"));
       

        $query->setParameter('user', $user_id);
        return $query->getQuery()->getResult();
    }
     public function getEvaluation1($soumission_id,$user_id) {
        $query = $this->createQueryBuilder("d");
        $query->select('d');
      
        $query->Where($query->expr()->in('d.id', "SELECT d2.id FROM tuto\BackofficeBundle\Entity\EvaluationReponse d2 INNER JOIN d2.evaluation p WHERE p.soumission = :soumission AND p.user=:user"));
       

        $query->setParameter('user', $user_id);
        $query->setParameter('soumission', $soumission_id);
        return $query->getQuery()->getResult();
    }
}
