<?php

namespace tuto\BackofficeBundle\Repository;

/**
 * MembreorgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreorgRepository extends \Doctrine\ORM\EntityRepository
{
}
