<?php

namespace tuto\BackofficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SoumissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoumissionRepository extends EntityRepository
{
    public function findByetat()
	{
		$query = $this->createQueryBuilder('p');
		$query->SELECT ('p') ;
		$query->where('p.etat = 1');
		
        return $query->getQuery()->getResult();
	}
       
        public function count()
	{
		$query = $this->createQueryBuilder('n');
		$query->SELECT ('COUNT(n)');
		$query->where('n.etat = 1');
        return $query->getQuery()->getSingleScalarResult();
        
	}
         public function getSoumissionNonLu($user_id) {
        $query = $this->createQueryBuilder("d");
        $query->select('d');
      
        $query->Where($query->expr()->in('d.id', "SELECT d2.id FROM tuto\BackofficeBundle\Entity\Soumission d2 INNER JOIN d2.user p WHERE p.id = :user"));
       

        $query->setParameter('user', $user_id);
        return $query->getQuery()->getResult();
    }
    public function getNb($type_id)
	{
		$query = $this->createQueryBuilder('u');
		$query->SELECT ('COUNT(u)');
		
		$query->where('u.type = :id');
		$query->setParameter('id',$type_id);

        return $query->getQuery()->getSingleScalarResult();

	}
}


