<?php

namespace tuto\BackofficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function getNbprof($role) {
        $query = $this->createQueryBuilder('u');
        $query->SELECT('COUNT(u)');
        $query->where('u.roles LIKE :roles');
        $query->setParameter('roles', '%"' . $role . '"%');
        return $query->getQuery()->getSingleScalarResult();
    }
    public function count($role)
	{
		$query = $this->createQueryBuilder('n');
		$query->SELECT ('COUNT(n)');
		$query->where('n.etat = 3');
                $query->andWhere('n.roles LIKE :roles');
        $query->setParameter('roles', '%"' . $role . '"%');
        return $query->getQuery()->getSingleScalarResult();
        
	}
          public function findByetat($role)
	{
		$query = $this->createQueryBuilder('p');
		$query->SELECT ('p') ;
		$query->where('p.etat = 3');
                $query->andWhere('p.roles LIKE :roles');
        $query->setParameter('roles', '%"' . $role . '"%');
		
        return $query->getQuery()->getResult();
	}

}
